name: Publish Site
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: apt-get install pngquant 
      - run: pip install -r requirements.txt
        working-directory: site
      - run: mkdocs gh-deploy --force
        working-directory: site
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }} 
